// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_renderer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "svg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_map_5frenderer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_map_5frenderer_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_map_5frenderer_2eproto;
namespace TransCatSerial {
class MapRendererContext;
struct MapRendererContextDefaultTypeInternal;
extern MapRendererContextDefaultTypeInternal _MapRendererContext_default_instance_;
class RouterContext;
struct RouterContextDefaultTypeInternal;
extern RouterContextDefaultTypeInternal _RouterContext_default_instance_;
}  // namespace TransCatSerial
PROTOBUF_NAMESPACE_OPEN
template<> ::TransCatSerial::MapRendererContext* Arena::CreateMaybeMessage<::TransCatSerial::MapRendererContext>(Arena*);
template<> ::TransCatSerial::RouterContext* Arena::CreateMaybeMessage<::TransCatSerial::RouterContext>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TransCatSerial {

// ===================================================================

class MapRendererContext final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TransCatSerial.MapRendererContext) */ {
 public:
  inline MapRendererContext() : MapRendererContext(nullptr) {}
  ~MapRendererContext() override;
  explicit constexpr MapRendererContext(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapRendererContext(const MapRendererContext& from);
  MapRendererContext(MapRendererContext&& from) noexcept
    : MapRendererContext() {
    *this = ::std::move(from);
  }

  inline MapRendererContext& operator=(const MapRendererContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapRendererContext& operator=(MapRendererContext&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapRendererContext& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapRendererContext* internal_default_instance() {
    return reinterpret_cast<const MapRendererContext*>(
               &_MapRendererContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapRendererContext& a, MapRendererContext& b) {
    a.Swap(&b);
  }
  inline void Swap(MapRendererContext* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapRendererContext* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapRendererContext* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MapRendererContext>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MapRendererContext& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const MapRendererContext& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapRendererContext* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TransCatSerial.MapRendererContext";
  }
  protected:
  explicit MapRendererContext(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColorPaletteFieldNumber = 12,
    kBusLabelOffsetFieldNumber = 7,
    kStopLabelOffsetFieldNumber = 9,
    kUnderlayerColorFieldNumber = 10,
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kPaddingFieldNumber = 3,
    kLineWidthFieldNumber = 4,
    kStopRadiusFieldNumber = 5,
    kBusLabelFontSizeFieldNumber = 6,
    kStopLabelFontSizeFieldNumber = 8,
    kUnderlayerWidthFieldNumber = 11,
  };
  // repeated .TransCatSerial.Color color_palette = 12;
  int color_palette_size() const;
  private:
  int _internal_color_palette_size() const;
  public:
  void clear_color_palette();
  ::TransCatSerial::Color* mutable_color_palette(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TransCatSerial::Color >*
      mutable_color_palette();
  private:
  const ::TransCatSerial::Color& _internal_color_palette(int index) const;
  ::TransCatSerial::Color* _internal_add_color_palette();
  public:
  const ::TransCatSerial::Color& color_palette(int index) const;
  ::TransCatSerial::Color* add_color_palette();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TransCatSerial::Color >&
      color_palette() const;

  // .TransCatSerial.Point bus_label_offset = 7;
  bool has_bus_label_offset() const;
  private:
  bool _internal_has_bus_label_offset() const;
  public:
  void clear_bus_label_offset();
  const ::TransCatSerial::Point& bus_label_offset() const;
  PROTOBUF_NODISCARD ::TransCatSerial::Point* release_bus_label_offset();
  ::TransCatSerial::Point* mutable_bus_label_offset();
  void set_allocated_bus_label_offset(::TransCatSerial::Point* bus_label_offset);
  private:
  const ::TransCatSerial::Point& _internal_bus_label_offset() const;
  ::TransCatSerial::Point* _internal_mutable_bus_label_offset();
  public:
  void unsafe_arena_set_allocated_bus_label_offset(
      ::TransCatSerial::Point* bus_label_offset);
  ::TransCatSerial::Point* unsafe_arena_release_bus_label_offset();

  // .TransCatSerial.Point stop_label_offset = 9;
  bool has_stop_label_offset() const;
  private:
  bool _internal_has_stop_label_offset() const;
  public:
  void clear_stop_label_offset();
  const ::TransCatSerial::Point& stop_label_offset() const;
  PROTOBUF_NODISCARD ::TransCatSerial::Point* release_stop_label_offset();
  ::TransCatSerial::Point* mutable_stop_label_offset();
  void set_allocated_stop_label_offset(::TransCatSerial::Point* stop_label_offset);
  private:
  const ::TransCatSerial::Point& _internal_stop_label_offset() const;
  ::TransCatSerial::Point* _internal_mutable_stop_label_offset();
  public:
  void unsafe_arena_set_allocated_stop_label_offset(
      ::TransCatSerial::Point* stop_label_offset);
  ::TransCatSerial::Point* unsafe_arena_release_stop_label_offset();

  // .TransCatSerial.Color underlayer_color = 10;
  bool has_underlayer_color() const;
  private:
  bool _internal_has_underlayer_color() const;
  public:
  void clear_underlayer_color();
  const ::TransCatSerial::Color& underlayer_color() const;
  PROTOBUF_NODISCARD ::TransCatSerial::Color* release_underlayer_color();
  ::TransCatSerial::Color* mutable_underlayer_color();
  void set_allocated_underlayer_color(::TransCatSerial::Color* underlayer_color);
  private:
  const ::TransCatSerial::Color& _internal_underlayer_color() const;
  ::TransCatSerial::Color* _internal_mutable_underlayer_color();
  public:
  void unsafe_arena_set_allocated_underlayer_color(
      ::TransCatSerial::Color* underlayer_color);
  ::TransCatSerial::Color* unsafe_arena_release_underlayer_color();

  // double width = 1;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // double height = 2;
  void clear_height();
  double height() const;
  void set_height(double value);
  private:
  double _internal_height() const;
  void _internal_set_height(double value);
  public:

  // double padding = 3;
  void clear_padding();
  double padding() const;
  void set_padding(double value);
  private:
  double _internal_padding() const;
  void _internal_set_padding(double value);
  public:

  // double line_width = 4;
  void clear_line_width();
  double line_width() const;
  void set_line_width(double value);
  private:
  double _internal_line_width() const;
  void _internal_set_line_width(double value);
  public:

  // double stop_radius = 5;
  void clear_stop_radius();
  double stop_radius() const;
  void set_stop_radius(double value);
  private:
  double _internal_stop_radius() const;
  void _internal_set_stop_radius(double value);
  public:

  // int32 bus_label_font_size = 6;
  void clear_bus_label_font_size();
  int32_t bus_label_font_size() const;
  void set_bus_label_font_size(int32_t value);
  private:
  int32_t _internal_bus_label_font_size() const;
  void _internal_set_bus_label_font_size(int32_t value);
  public:

  // int32 stop_label_font_size = 8;
  void clear_stop_label_font_size();
  int32_t stop_label_font_size() const;
  void set_stop_label_font_size(int32_t value);
  private:
  int32_t _internal_stop_label_font_size() const;
  void _internal_set_stop_label_font_size(int32_t value);
  public:

  // double underlayer_width = 11;
  void clear_underlayer_width();
  double underlayer_width() const;
  void set_underlayer_width(double value);
  private:
  double _internal_underlayer_width() const;
  void _internal_set_underlayer_width(double value);
  public:

  // @@protoc_insertion_point(class_scope:TransCatSerial.MapRendererContext)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TransCatSerial::Color > color_palette_;
  ::TransCatSerial::Point* bus_label_offset_;
  ::TransCatSerial::Point* stop_label_offset_;
  ::TransCatSerial::Color* underlayer_color_;
  double width_;
  double height_;
  double padding_;
  double line_width_;
  double stop_radius_;
  int32_t bus_label_font_size_;
  int32_t stop_label_font_size_;
  double underlayer_width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// -------------------------------------------------------------------

class RouterContext final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TransCatSerial.RouterContext) */ {
 public:
  inline RouterContext() : RouterContext(nullptr) {}
  ~RouterContext() override;
  explicit constexpr RouterContext(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RouterContext(const RouterContext& from);
  RouterContext(RouterContext&& from) noexcept
    : RouterContext() {
    *this = ::std::move(from);
  }

  inline RouterContext& operator=(const RouterContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline RouterContext& operator=(RouterContext&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RouterContext& default_instance() {
    return *internal_default_instance();
  }
  static inline const RouterContext* internal_default_instance() {
    return reinterpret_cast<const RouterContext*>(
               &_RouterContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RouterContext& a, RouterContext& b) {
    a.Swap(&b);
  }
  inline void Swap(RouterContext* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RouterContext* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RouterContext* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RouterContext>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RouterContext& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RouterContext& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RouterContext* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TransCatSerial.RouterContext";
  }
  protected:
  explicit RouterContext(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBusWaitTimeFieldNumber = 1,
    kBusVelocityFieldNumber = 2,
  };
  // double bus_wait_time = 1;
  void clear_bus_wait_time();
  double bus_wait_time() const;
  void set_bus_wait_time(double value);
  private:
  double _internal_bus_wait_time() const;
  void _internal_set_bus_wait_time(double value);
  public:

  // double bus_velocity = 2;
  void clear_bus_velocity();
  double bus_velocity() const;
  void set_bus_velocity(double value);
  private:
  double _internal_bus_velocity() const;
  void _internal_set_bus_velocity(double value);
  public:

  // @@protoc_insertion_point(class_scope:TransCatSerial.RouterContext)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double bus_wait_time_;
  double bus_velocity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapRendererContext

// double width = 1;
inline void MapRendererContext::clear_width() {
  width_ = 0;
}
inline double MapRendererContext::_internal_width() const {
  return width_;
}
inline double MapRendererContext::width() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.width)
  return _internal_width();
}
inline void MapRendererContext::_internal_set_width(double value) {
  
  width_ = value;
}
inline void MapRendererContext::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.width)
}

// double height = 2;
inline void MapRendererContext::clear_height() {
  height_ = 0;
}
inline double MapRendererContext::_internal_height() const {
  return height_;
}
inline double MapRendererContext::height() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.height)
  return _internal_height();
}
inline void MapRendererContext::_internal_set_height(double value) {
  
  height_ = value;
}
inline void MapRendererContext::set_height(double value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.height)
}

// double padding = 3;
inline void MapRendererContext::clear_padding() {
  padding_ = 0;
}
inline double MapRendererContext::_internal_padding() const {
  return padding_;
}
inline double MapRendererContext::padding() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.padding)
  return _internal_padding();
}
inline void MapRendererContext::_internal_set_padding(double value) {
  
  padding_ = value;
}
inline void MapRendererContext::set_padding(double value) {
  _internal_set_padding(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.padding)
}

// double line_width = 4;
inline void MapRendererContext::clear_line_width() {
  line_width_ = 0;
}
inline double MapRendererContext::_internal_line_width() const {
  return line_width_;
}
inline double MapRendererContext::line_width() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.line_width)
  return _internal_line_width();
}
inline void MapRendererContext::_internal_set_line_width(double value) {
  
  line_width_ = value;
}
inline void MapRendererContext::set_line_width(double value) {
  _internal_set_line_width(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.line_width)
}

// double stop_radius = 5;
inline void MapRendererContext::clear_stop_radius() {
  stop_radius_ = 0;
}
inline double MapRendererContext::_internal_stop_radius() const {
  return stop_radius_;
}
inline double MapRendererContext::stop_radius() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.stop_radius)
  return _internal_stop_radius();
}
inline void MapRendererContext::_internal_set_stop_radius(double value) {
  
  stop_radius_ = value;
}
inline void MapRendererContext::set_stop_radius(double value) {
  _internal_set_stop_radius(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.stop_radius)
}

// int32 bus_label_font_size = 6;
inline void MapRendererContext::clear_bus_label_font_size() {
  bus_label_font_size_ = 0;
}
inline int32_t MapRendererContext::_internal_bus_label_font_size() const {
  return bus_label_font_size_;
}
inline int32_t MapRendererContext::bus_label_font_size() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.bus_label_font_size)
  return _internal_bus_label_font_size();
}
inline void MapRendererContext::_internal_set_bus_label_font_size(int32_t value) {
  
  bus_label_font_size_ = value;
}
inline void MapRendererContext::set_bus_label_font_size(int32_t value) {
  _internal_set_bus_label_font_size(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.bus_label_font_size)
}

// .TransCatSerial.Point bus_label_offset = 7;
inline bool MapRendererContext::_internal_has_bus_label_offset() const {
  return this != internal_default_instance() && bus_label_offset_ != nullptr;
}
inline bool MapRendererContext::has_bus_label_offset() const {
  return _internal_has_bus_label_offset();
}
inline const ::TransCatSerial::Point& MapRendererContext::_internal_bus_label_offset() const {
  const ::TransCatSerial::Point* p = bus_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::TransCatSerial::Point&>(
      ::TransCatSerial::_Point_default_instance_);
}
inline const ::TransCatSerial::Point& MapRendererContext::bus_label_offset() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.bus_label_offset)
  return _internal_bus_label_offset();
}
inline void MapRendererContext::unsafe_arena_set_allocated_bus_label_offset(
    ::TransCatSerial::Point* bus_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bus_label_offset_);
  }
  bus_label_offset_ = bus_label_offset;
  if (bus_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TransCatSerial.MapRendererContext.bus_label_offset)
}
inline ::TransCatSerial::Point* MapRendererContext::release_bus_label_offset() {
  
  ::TransCatSerial::Point* temp = bus_label_offset_;
  bus_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::TransCatSerial::Point* MapRendererContext::unsafe_arena_release_bus_label_offset() {
  // @@protoc_insertion_point(field_release:TransCatSerial.MapRendererContext.bus_label_offset)
  
  ::TransCatSerial::Point* temp = bus_label_offset_;
  bus_label_offset_ = nullptr;
  return temp;
}
inline ::TransCatSerial::Point* MapRendererContext::_internal_mutable_bus_label_offset() {
  
  if (bus_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::TransCatSerial::Point>(GetArenaForAllocation());
    bus_label_offset_ = p;
  }
  return bus_label_offset_;
}
inline ::TransCatSerial::Point* MapRendererContext::mutable_bus_label_offset() {
  ::TransCatSerial::Point* _msg = _internal_mutable_bus_label_offset();
  // @@protoc_insertion_point(field_mutable:TransCatSerial.MapRendererContext.bus_label_offset)
  return _msg;
}
inline void MapRendererContext::set_allocated_bus_label_offset(::TransCatSerial::Point* bus_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(bus_label_offset_);
  }
  if (bus_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bus_label_offset));
    if (message_arena != submessage_arena) {
      bus_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bus_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  bus_label_offset_ = bus_label_offset;
  // @@protoc_insertion_point(field_set_allocated:TransCatSerial.MapRendererContext.bus_label_offset)
}

// int32 stop_label_font_size = 8;
inline void MapRendererContext::clear_stop_label_font_size() {
  stop_label_font_size_ = 0;
}
inline int32_t MapRendererContext::_internal_stop_label_font_size() const {
  return stop_label_font_size_;
}
inline int32_t MapRendererContext::stop_label_font_size() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.stop_label_font_size)
  return _internal_stop_label_font_size();
}
inline void MapRendererContext::_internal_set_stop_label_font_size(int32_t value) {
  
  stop_label_font_size_ = value;
}
inline void MapRendererContext::set_stop_label_font_size(int32_t value) {
  _internal_set_stop_label_font_size(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.stop_label_font_size)
}

// .TransCatSerial.Point stop_label_offset = 9;
inline bool MapRendererContext::_internal_has_stop_label_offset() const {
  return this != internal_default_instance() && stop_label_offset_ != nullptr;
}
inline bool MapRendererContext::has_stop_label_offset() const {
  return _internal_has_stop_label_offset();
}
inline const ::TransCatSerial::Point& MapRendererContext::_internal_stop_label_offset() const {
  const ::TransCatSerial::Point* p = stop_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::TransCatSerial::Point&>(
      ::TransCatSerial::_Point_default_instance_);
}
inline const ::TransCatSerial::Point& MapRendererContext::stop_label_offset() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.stop_label_offset)
  return _internal_stop_label_offset();
}
inline void MapRendererContext::unsafe_arena_set_allocated_stop_label_offset(
    ::TransCatSerial::Point* stop_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stop_label_offset_);
  }
  stop_label_offset_ = stop_label_offset;
  if (stop_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TransCatSerial.MapRendererContext.stop_label_offset)
}
inline ::TransCatSerial::Point* MapRendererContext::release_stop_label_offset() {
  
  ::TransCatSerial::Point* temp = stop_label_offset_;
  stop_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::TransCatSerial::Point* MapRendererContext::unsafe_arena_release_stop_label_offset() {
  // @@protoc_insertion_point(field_release:TransCatSerial.MapRendererContext.stop_label_offset)
  
  ::TransCatSerial::Point* temp = stop_label_offset_;
  stop_label_offset_ = nullptr;
  return temp;
}
inline ::TransCatSerial::Point* MapRendererContext::_internal_mutable_stop_label_offset() {
  
  if (stop_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::TransCatSerial::Point>(GetArenaForAllocation());
    stop_label_offset_ = p;
  }
  return stop_label_offset_;
}
inline ::TransCatSerial::Point* MapRendererContext::mutable_stop_label_offset() {
  ::TransCatSerial::Point* _msg = _internal_mutable_stop_label_offset();
  // @@protoc_insertion_point(field_mutable:TransCatSerial.MapRendererContext.stop_label_offset)
  return _msg;
}
inline void MapRendererContext::set_allocated_stop_label_offset(::TransCatSerial::Point* stop_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(stop_label_offset_);
  }
  if (stop_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stop_label_offset));
    if (message_arena != submessage_arena) {
      stop_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stop_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  stop_label_offset_ = stop_label_offset;
  // @@protoc_insertion_point(field_set_allocated:TransCatSerial.MapRendererContext.stop_label_offset)
}

// .TransCatSerial.Color underlayer_color = 10;
inline bool MapRendererContext::_internal_has_underlayer_color() const {
  return this != internal_default_instance() && underlayer_color_ != nullptr;
}
inline bool MapRendererContext::has_underlayer_color() const {
  return _internal_has_underlayer_color();
}
inline const ::TransCatSerial::Color& MapRendererContext::_internal_underlayer_color() const {
  const ::TransCatSerial::Color* p = underlayer_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::TransCatSerial::Color&>(
      ::TransCatSerial::_Color_default_instance_);
}
inline const ::TransCatSerial::Color& MapRendererContext::underlayer_color() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.underlayer_color)
  return _internal_underlayer_color();
}
inline void MapRendererContext::unsafe_arena_set_allocated_underlayer_color(
    ::TransCatSerial::Color* underlayer_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(underlayer_color_);
  }
  underlayer_color_ = underlayer_color;
  if (underlayer_color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TransCatSerial.MapRendererContext.underlayer_color)
}
inline ::TransCatSerial::Color* MapRendererContext::release_underlayer_color() {
  
  ::TransCatSerial::Color* temp = underlayer_color_;
  underlayer_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::TransCatSerial::Color* MapRendererContext::unsafe_arena_release_underlayer_color() {
  // @@protoc_insertion_point(field_release:TransCatSerial.MapRendererContext.underlayer_color)
  
  ::TransCatSerial::Color* temp = underlayer_color_;
  underlayer_color_ = nullptr;
  return temp;
}
inline ::TransCatSerial::Color* MapRendererContext::_internal_mutable_underlayer_color() {
  
  if (underlayer_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::TransCatSerial::Color>(GetArenaForAllocation());
    underlayer_color_ = p;
  }
  return underlayer_color_;
}
inline ::TransCatSerial::Color* MapRendererContext::mutable_underlayer_color() {
  ::TransCatSerial::Color* _msg = _internal_mutable_underlayer_color();
  // @@protoc_insertion_point(field_mutable:TransCatSerial.MapRendererContext.underlayer_color)
  return _msg;
}
inline void MapRendererContext::set_allocated_underlayer_color(::TransCatSerial::Color* underlayer_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(underlayer_color_);
  }
  if (underlayer_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(underlayer_color));
    if (message_arena != submessage_arena) {
      underlayer_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, underlayer_color, submessage_arena);
    }
    
  } else {
    
  }
  underlayer_color_ = underlayer_color;
  // @@protoc_insertion_point(field_set_allocated:TransCatSerial.MapRendererContext.underlayer_color)
}

// double underlayer_width = 11;
inline void MapRendererContext::clear_underlayer_width() {
  underlayer_width_ = 0;
}
inline double MapRendererContext::_internal_underlayer_width() const {
  return underlayer_width_;
}
inline double MapRendererContext::underlayer_width() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.underlayer_width)
  return _internal_underlayer_width();
}
inline void MapRendererContext::_internal_set_underlayer_width(double value) {
  
  underlayer_width_ = value;
}
inline void MapRendererContext::set_underlayer_width(double value) {
  _internal_set_underlayer_width(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.MapRendererContext.underlayer_width)
}

// repeated .TransCatSerial.Color color_palette = 12;
inline int MapRendererContext::_internal_color_palette_size() const {
  return color_palette_.size();
}
inline int MapRendererContext::color_palette_size() const {
  return _internal_color_palette_size();
}
inline ::TransCatSerial::Color* MapRendererContext::mutable_color_palette(int index) {
  // @@protoc_insertion_point(field_mutable:TransCatSerial.MapRendererContext.color_palette)
  return color_palette_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TransCatSerial::Color >*
MapRendererContext::mutable_color_palette() {
  // @@protoc_insertion_point(field_mutable_list:TransCatSerial.MapRendererContext.color_palette)
  return &color_palette_;
}
inline const ::TransCatSerial::Color& MapRendererContext::_internal_color_palette(int index) const {
  return color_palette_.Get(index);
}
inline const ::TransCatSerial::Color& MapRendererContext::color_palette(int index) const {
  // @@protoc_insertion_point(field_get:TransCatSerial.MapRendererContext.color_palette)
  return _internal_color_palette(index);
}
inline ::TransCatSerial::Color* MapRendererContext::_internal_add_color_palette() {
  return color_palette_.Add();
}
inline ::TransCatSerial::Color* MapRendererContext::add_color_palette() {
  ::TransCatSerial::Color* _add = _internal_add_color_palette();
  // @@protoc_insertion_point(field_add:TransCatSerial.MapRendererContext.color_palette)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TransCatSerial::Color >&
MapRendererContext::color_palette() const {
  // @@protoc_insertion_point(field_list:TransCatSerial.MapRendererContext.color_palette)
  return color_palette_;
}

// -------------------------------------------------------------------

// RouterContext

// double bus_wait_time = 1;
inline void RouterContext::clear_bus_wait_time() {
  bus_wait_time_ = 0;
}
inline double RouterContext::_internal_bus_wait_time() const {
  return bus_wait_time_;
}
inline double RouterContext::bus_wait_time() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.RouterContext.bus_wait_time)
  return _internal_bus_wait_time();
}
inline void RouterContext::_internal_set_bus_wait_time(double value) {
  
  bus_wait_time_ = value;
}
inline void RouterContext::set_bus_wait_time(double value) {
  _internal_set_bus_wait_time(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.RouterContext.bus_wait_time)
}

// double bus_velocity = 2;
inline void RouterContext::clear_bus_velocity() {
  bus_velocity_ = 0;
}
inline double RouterContext::_internal_bus_velocity() const {
  return bus_velocity_;
}
inline double RouterContext::bus_velocity() const {
  // @@protoc_insertion_point(field_get:TransCatSerial.RouterContext.bus_velocity)
  return _internal_bus_velocity();
}
inline void RouterContext::_internal_set_bus_velocity(double value) {
  
  bus_velocity_ = value;
}
inline void RouterContext::set_bus_velocity(double value) {
  _internal_set_bus_velocity(value);
  // @@protoc_insertion_point(field_set:TransCatSerial.RouterContext.bus_velocity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace TransCatSerial

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
